### ISSUE TITLE
Omission of bump lib for collisions?

### ISSUE THREAD

**Issue by prust** [bakpakin/weregoat#1]
@bakpakin: I like what I've seen so far of Tiny ECS and I see this game and https://github.com/bakpakin/CommandoKibbles as examples of how to use Tiny ECS with some of the top LÖVE libraries, so I've been considering drawing from these games to create a framework for LÖVE games that builds on Tiny ECS, gamera, gamestate, anim8, sti, etc.

One curious significant difference between this and CommandoKibbles is the omission of the bump library. Is that because you no longer prefer this library or because it did not work well for this particular game, or just because this game's needs were so rudimentary that they could all be handled by the 60-line CollisionSystem.lua?

**Comment by bakpakin** [comment]
There is no specific reason for the omission other than that I didn't want or need the full bump library. Bump would have been easier to use, though, and would probably have worked fine. Hindsight is 20/20.

**Comment by prust** [comment]
@bakpakin: Thanks for the response!
